apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: kube-system
  labels:
    app: login-nginx
  name: login-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: login-nginx
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: login-nginx
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: login-nginx
              topologyKey: kubernetes.io/hostname
      containers:
      - image: 381492217459.dkr.ecr.ap-northeast-2.amazonaws.com/login-nginx:v1.0
        name: login-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          requests:
            memory: 500Mi
            cpu: 200m
          limits:
            memory: 1Gi
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: kube-system
  labels:
    app: login-nginx
  name: login-nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: login-nginx
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: login-nginx-hpa
  namespace: kube-system
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: login-nginx
  targetCPUUtilizationPercentage: 20
