apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: kube-system
  labels:
    app: mypage-nginx
  name: mypage-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mypage-nginx
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: mypage-nginx
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: mypage-nginx
              topologyKey: kubernetes.io/hostname
      containers:
      - image: 381492217459.dkr.ecr.ap-northeast-2.amazonaws.com/mypage-nginx:v3.0
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          requests:
            memory: 50Mi
            cpu: 100m
          limits:
            memory: 50Gi
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: kube-system
  labels:
    app: mypage-nginx
  name: mypage-nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mypage-nginx
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mypage-nginx-hpa
  namespace: kube-system
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mypage-nginx
  targetCPUUtilizationPercentage: 50
