apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: login-tomcat
  name: login-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-tomcat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: login-tomcat
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: login-tomcat
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: login-tomcat
              topologyKey: kubernetes.io/hostname
      containers:
      - image: 637423608085.dkr.ecr.ap-northeast-2.amazonaws.com/login-tomcat:v5.0
        name: login-tomcat
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          requests:
            memory: 500Mi
            cpu: 200m
          limits:
            memory: 1Gi
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: login-tomcat
  name: login-tomcat-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: login-tomcat
  type: ClusterIP
  clusterIP: 172.20.20.200
status:
  loadBalancer: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: login-tomcat-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: login-tomcat
  targetCPUUtilizationPercentage: 20
